name: CI

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  buid:
    name: build
    runs-on: ubuntu-24.04-arm
    container:
      image: alpine
      volumes:
        - /tmp:/tmp:rw,rshared
        - /tmp:/__e/node20:ro,rshared
    steps:
      - name: Allow Linux musl containers on ARM64 runners
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs build-base --update-cache
          mkdir -p /tmp/bin
          ln -s /usr/bin/node /tmp/bin/node
      - name: chekout
        uses: actions/checkout@v4
      - name: compile
        run: gcc test.c -o test
